# Training Configuration for BLIP Clock Time Reading

# Model Configuration
model:
  name: "Salesforce/blip-image-captioning-base"
  max_length: 32
  
# Data Configuration  
data:
  train_dir: "./data/train"
  valid_dir: "./data/valid" 
  test_dir: "./data/test"
  image_size: 224
  batch_size: 8
  num_workers: 4

# Training Parameters
training:
  epochs: 3
  learning_rate: 3e-5
  weight_decay: 0.01
  warmup_steps: 50
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0
  
# Optimizer
optimizer:
  name: "AdamW"
  betas: [0.9, 0.999]
  eps: 1e-8

# Scheduler
scheduler:
  name: "linear"
  warmup_ratio: 0.1

# Logging and Checkpointing
logging:
  log_every: 100
  eval_every: 500
  save_every: 1000
  output_dir: "./models"
  experiment_name: "blip-clock-final"
  
# Evaluation
evaluation:
  metric: "accuracy"
  early_stopping_patience: 3
  
# Hardware
hardware:
  device: "auto"  # auto, cpu, cuda
  mixed_precision: true
  dataloader_pin_memory: true

# Reproducibility
seed: 42

# Generation Parameters (for inference)
generation:
  do_sample: false
  repetition_penalty: 1.2
  max_new_tokens: 10
  temperature: 1.0
